rootProject.name = "visulog"
include("webgen")
include("git")
include("github")
include("pluginmanager")
include("config")
include("analyzer")
include("cli")
include("chartbuilder")
include("analyzer")
include("hq")
include("gitlab")
