@startuml


cloud Github as githubapi
cloud Gitlab as gitlabapi
actor User as user

node "Local machine" {
  component Analyzer as analyzer
  component ChartBuilder as chartbuilder
  component CLI as cli
  component Config as config
  component Git as git
  component Github as github
  component Gitlab as gitlab
  component GUI as gui
  component Mercurial as hq
  component PluginManager as pluginmanager
  component WebGeneretor as webgen
  component TableBuilder as tablebuilder
  component CSVBuilder as csvbuilder
  storage "File system" as fs
}

cli -> config

config -> webgen
config -> chartbuilder
config -> analyzer
config -> tablebuilder
config -> csvbuilder

tablebuilder -> analyzer
analyzer -> pluginmanager

pluginmanager -> git

chartbuilder -> analyzer



git -> fs

github -> githubapi
gitlab -> gitlabapi

gui -> chartbuilder

hq -> fs

webgen -> chartbuilder

user -> cli
@enduml
